### PR TITLE
Branch alpha bug remark

### LINKED ISSUE #163: Remark command shows unclear error message for multiple rm/fields
The `remark` command correctly prevents multiple `rm/` fields, but the error message shown is generic and not very helpful. Users might not immediately understand that the issue is the presence of multiple `rm/` fields.

Steps to reproduce:
1. Ensure there is at least one person in the displayed list.
2. Run the command:
`remark 1 rm/first remark rm/second remark`
3. Observe the error message shown in the display box.

Expected behaviour:
- The app should display a specific error indicating multiple values were provided for a single-valued field, e.g.:
` Multiple values specified for the single-valued field: rm/`

Actual behaviour:
- The app shows a generic `Invalid command format!` message with the command usage instructions

### PR DESCRIPTION
**Pull request by Kimberlee97**
Fixes #163

### CODE REVIEW

**Review by zhiyu05 — APPROVED** [review]
LGTM!

File: src/main/java/homey/logic/parser/RemarkCommandParser.java [hunk 1]
```diff
@@ -53,7 +54,7 @@ private Index parseIndex(ArgumentMultimap argMultimap) throws ParseException {
     private void validatePrefix(ArgumentMultimap argMultimap) throws ParseException {
         if (argMultimap.getAllValues(PREFIX_REMARK).size() > 1) {
             throw new ParseException(
-                    String.format(MESSAGE_INVALID_COMMAND_FORMAT, RemarkCommand.MESSAGE_USAGE));
+                    getErrorMessageForDuplicatePrefixes(PREFIX_REMARK));
```
Comment (zhiyu05) [inline src/main/java/homey/logic/parser/RemarkCommandParser.java]: Could replace this method with verifyNoDuplicatePrefixesFor() from ArgumentMultimap to avoid duplicating existing functionality
